PreventPacketFly: true
KickForPacketFly: true
PacketFlyKickMessage: "&4PacketFly prevented on this server!"
MaxPacketsTeleport: 25
LogPacketFlyEvents: false

BoatflyPatch: true
LogBoatFlyEvents: false

PreventPortalTraps: true